### PR TITLE
Add Wireframes Folder

### PR DESCRIPTION
**Pull request by AurumValian**
This PR adds a new folder named wireframes, which contains images of our hand-drawn wireframes.

### CODE REVIEW

**Review by leighlars — COMMENTED** [review]
Not sure if this is a Github issue or a file storage issue, but I can't see the images!

**Review by Estaffieri — CHANGES_REQUESTED** [review]
Looks like these images are not being pushed up to Github? Not sure where the disconnect is happening.

**Comment by AurumValian** [comment]
Strange... They open on GitHub on my end. I'll tinker with it in a bit.

**Comment by AurumValian** [comment]
@leighlars @Estaffieri  Changes have been made!

**Review by Estaffieri — APPROVED** [review]

**Review by leighlars — APPROVED** [review]
Thanks for resizing the images!

**Comment by Estaffieri** [comment]
These images looks good! Thank you for getting those together!

**Pull request merged**
